FROM microsoft/dotnet:2.0-sdk
WORKDIR /app

ADD . /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN HelloWorld restore

# copy and build everything else
COPY . ./
RUN HelloWorld  publish -c Release -o out
ENTRYPOINT ["HelloWorld", "out/Hello.dll"]
CMD ["dotnet", "HelloWorld/helloWorld/Startup.cs"]
